"""MiDaS depth estimation module for dump fill classification.

This module estimates relative scene depth from an input image and classifies
how full a dump area is based on the average depth value within the dump region.
It is intentionally independent from truck assignment and routing logic so it can
be imported directly by the Planning Agent.
"""

from __future__ import annotations

from typing import Any, Dict, List, Tuple

import cv2
import numpy as np
import torch

from config import EMPTY_THRESHOLD, FULL_THRESHOLD, HALF_FILLED_THRESHOLD, MIDAS_MODEL_TYPE

try:
    from torchvision.transforms import functional as F
except ImportError:  # pragma: no cover
    F = None


class MiDaSDepthEstimator:
    """Estimate relative depth using a MiDaS model and classify dump fill."""

    def __init__(
        self,
        model_type: str = MIDAS_MODEL_TYPE,
        device: str | None = None,
        empty_threshold: float = EMPTY_THRESHOLD,
        half_threshold: float = HALF_FILLED_THRESHOLD,
        full_threshold: float = FULL_THRESHOLD,
    ):
        """Initialize the depth estimator.

        Args:
            model_type: MiDaS model name supported by PyTorch Hub.
            device: Optional device string, such as ``cpu`` or ``cuda``.
            empty_threshold: Depth value threshold below which the dump is treated
                as empty.
            half_threshold: Depth value threshold below which the dump is treated
                as half-filled; otherwise it is fully filled.
        """
        self.model_type = model_type
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.empty_threshold = empty_threshold
        self.half_threshold = half_threshold
        self.full_threshold = full_threshold

        try:
            # Load the MiDaS model from PyTorch Hub. The model is lightweight and
            # suitable for depth estimation in an engineering prototype.
            self.model = torch.hub.load(
                "intel-isl/MiDaS",
                model_type,
                pretrained=True,
            ).to(self.device).eval()

            # The MiDaS repository expects the model to be paired with a
            # transformation pipeline for resizing and normalization.
            self.midas_transforms = torch.hub.load(
                "intel-isl/MiDaS",
                "transforms",
            )
        except Exception as exc:  # pragma: no cover
            raise RuntimeError(
                "Failed to load MiDaS model. Ensure PyTorch and the MiDaS repo are available."
            ) from exc

    def estimate_depth(self, image_path: str) -> np.ndarray:
        """Load an image and generate a relative depth map.

        Args:
            image_path: File path to the input image.

        Returns:
            A NumPy array representing the depth map.

        Raises:
            FileNotFoundError: If the input image does not exist.
            ValueError: If the image cannot be processed.
        """
        image = cv2.imread(image_path)
        if image is None:
            raise FileNotFoundError(f"Unable to load image: {image_path}")

        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        try:
            # Use the standard MiDaS preprocessing pipeline.
            input_batch = self.midas_transforms.to_tensor(image_rgb).unsqueeze(0).to(self.device)
            with torch.no_grad():
                prediction = self.model(input_batch)
                prediction = torch.nn.functional.interpolate(
                    prediction.unsqueeze(1),
                    size=image_rgb.shape[:2],
                    mode="bicubic",
                    align_corners=False,
                ).squeeze()
                depth_map = prediction.cpu().numpy()
        except Exception as exc:  # pragma: no cover
            raise ValueError(f"Depth estimation failed for image: {image_path}") from exc

        # Normalize to a 0-1 range for easier relative interpretation.
        depth_map = (depth_map - depth_map.min()) / (depth_map.max() - depth_map.min() + 1e-8)
        return depth_map.astype(np.float32)

    def classify_dump_fill(self, depth_map: np.ndarray, dump_bbox: List[float]) -> Dict[str, Any]:
        """Estimate the fill status of a dump region from a depth map.

        The average depth is computed inside the dump bounding box region. A lower
        average depth indicates a shallower/smaller filled region, while higher
        depth suggests a larger or more filled region.

        Args:
            depth_map: A 2D NumPy array generated by ``estimate_depth``.
            dump_bbox: Bounding box in the form ``[x1, y1, x2, y2]``.

        Returns:
            A dictionary containing the dump id, average depth, and fill status.
        """
        if depth_map is None or depth_map.size == 0:
            raise ValueError("Depth map is empty or invalid.")

        if len(dump_bbox) != 4:
            raise ValueError("Dump bounding box must contain exactly four values: [x1, y1, x2, y2].")

        x1, y1, x2, y2 = [int(round(v)) for v in dump_bbox]
        height, width = depth_map.shape[:2]

        # Clip the region to valid image bounds.
        x1 = max(0, min(x1, width - 1))
        y1 = max(0, min(y1, height - 1))
        x2 = max(0, min(x2, width - 1))
        y2 = max(0, min(y2, height - 1))

        # In case of reversed coordinates, normalize them.
        if x2 < x1:
            x1, x2 = x2, x1
        if y2 < y1:
            y1, y2 = y2, y1

        cropped = depth_map[y1:y2, x1:x2]
        if cropped.size == 0:
            raise ValueError("Dump bounding box does not overlap with the image region.")

        average_depth = float(np.mean(cropped))

        if average_depth <= self.empty_threshold:
            fill_status = "Empty"
        elif average_depth <= self.half_threshold:
            fill_status = "Half-Filled"
        elif average_depth <= self.full_threshold:
            fill_status = "Half-Filled"
        else:
            fill_status = "Fully Filled"

        return {
            "dump_id": 1,
            "average_depth": round(average_depth, 2),
            "fill_status": fill_status,
        }
